<?php

declare(strict_types=1);

namespace skyblock\entity\projectile;

use pocketmine\entity\Entity;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\projectile\Projectile;
use pocketmine\math\RayTraceResult;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;

class Fireball extends Projectile {
	protected function initEntity(CompoundTag $nbt): void {
		parent::initEntity($nbt);
		$this->setCanSaveWithChunk(false);
	}

	protected function getInitialSizeInfo(): EntitySizeInfo {
		return new EntitySizeInfo(1, 1);
	}

	protected function onHitEntity(
		Entity $entityHit,
		RayTraceResult $hitResult
	): void {
		//parent::onHitEntity($entityHit, $hitResult); // TODO: Change the autogenerated stub
	}

	public static function getNetworkTypeId(): string {
		return EntityIds::WITHER_SKULL;
	}
}
